services:
  dev-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: golden
      POSTGRES_DB: douradosdb
  test-db:
    image: postgres
    ports:
      - 7777:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: golden
      POSTGRES_DB: douradosdb
